/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nlptools;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
	System.out.println("Hello from test guts. We are running.");
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
